### ISSUE TITLE
meilisearch-setup isssue

### ISSUE THREAD

**Issue by Aromokeye** [meilisearch/meilisearch-digitalocean#115]
Meilisearch becomes unavailable after using this meilisearch-setup script on digital ocean. I can't seem to figure out the problem. It works when I create A record for the subdomain but once I proceed to setup and provide master key with certbot, the subdomain stops working with error 404

**Comment by eskombro** [comment]
Hi @Aromokeye 

It is normal that you receive a `404` error. Normally when you run this script, you are changing the MeiliSearch instance from `development` environment to `production`. When `production` is enabled, the dashboard that you normally see when requesting `/` is disabled, so MeiliSearch answers with a `not found` error. But this doesn't mean that your instance is not working, you can still do all the requests to MeiliSearch that you used to do before, as long as you are using the right API KEY.

I think it is normal that you read this 404 as a problem with the instance or configuration, and you are not the first one to come back with this feedback, so I created [this issue](https://github.com/meilisearch/MeiliSearch/issues/1235) in the MeiliSearch repo to see if we can find a better behavior in this situation. Don't hesitate to give your point of view :)

Thanks for the feedback and I hope this helps you!

**Comment by Aromokeye** [comment]
Thank you @eskombro. It seems the process of deploying the set-up script causes the 404 error. I intentionally tested it by choosing NO for both production and domain set-up yet error 404 was seen.

**Comment by eskombro** [comment]
Thanks for the update @Aromokeye, I'll do a check of the script to see what's happening.

**Comment by paligiannis** [comment]
Any update on the issue. I deal with the same issue. Also, I deployed that on Digitlocean and I got the same result.

**Comment by eskombro** [comment]
Hi @paligiannis and @Aromokeye 

This will very likely solve the issue:

https://github.com/meilisearch/cloud-scripts/issues/30#issuecomment-783782274

**Comment by paligiannis** [comment]
@eskombro it seems that ssl issue persists fres

**Comment by paligiannis** [comment]
@eskombro it seems ssl issue persists. 
1. fresh installed meilisearch through digital ocean marketplace 
2. also run correctly mailiseach setup
3. 46.101.18.140 this is the ip 
4. https://46.101.18.140 does not work

**Comment by eskombro** [comment]
@paligiannis 

We use certbot to provide SSL certificates. Certbot is based on Letsencrypt, who do not support SSL for bare IP address, so they require to use a domain name.

To make this work, you need to issue your certificates somewhere else, come back to the script, and when asked if you want to use certbot, you need to say NO. The you will be asked if you want to add your own certificates, and add them.
