### ISSUE TITLE
SSL Not working on digital ocean

### ISSUE THREAD

**Issue by paligiannis** [meilisearch/meilisearch-digitalocean#137]
I launched a new server **1 GB Memory / 1 Intel vCPU / 25 GB Disk / SFO3 - MeiliSearch 0.19.0 on Debian 10 (buster)** I run the script of production and my app is not working on https, the response is Connection refused.

**Comment by eskombro** [comment]
Hi @paligiannis 

There are a lot of reasons why this could be happening, is hard to tell without more information.

- Is HTTP working but not HTTPS? Or none of them?
- Do you get a 502 error if you navigate to your URL?
- Are you using a big dataset on it? 1 Gb may be too little memory for production (depending on your dataset of course)
- Finally, can you try connecting via SSH and do `systemctl status meilisearch`?

**Comment by paligiannis** [comment]
@eskombro thank you for replies and support!

_Is HTTP working but not HTTPS? Or none of them?_
Yes HTTPS is working correctly showing the dashboard. But when I use meilisearch-setup and follow the instructions HTTPS is not working

_Do you get a 502 error if you navigate to your URL?_
I get connection refused

_Are you using a big dataset on it? 1 Gb may be too little memory for production (depending on your dataset of course)_
No, its a fresh install on digital ocean, I haven't executed anything on the server, absolutely nothing, it's a brand new server installed from the one click marketplace of digital ocean.

_Finally, can you try connecting via SSH and do systemctl status meilisearch?_
Its giving me the following answer:
● meilisearch.service - MeiliSearch
   Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-03-01 18:42:38 UTC; 14min ago

**Comment by eskombro** [comment]
Thanks @paligiannis 

I was mislead. I read [your comment](https://github.com/meilisearch/meilisearch-digitalocean/issues/115#issuecomment-788181536) on #115 and answered, just copying it here to leave a trace in case and moving that discussion here since they don't seem to be related:

> @eskombro it seems ssl issue persists.
> 
>     1. fresh installed meilisearch through digital ocean marketplace
>     2. also run correctly mailiseach setup
>     3. 46.101.18.140 this is the ip
>     4. https://46.101.18.140 does not work 

___

> We use certbot to provide SSL certificates. Certbot is based on Letsencrypt, which [doesn't support SSL for bare IP address](https://community.letsencrypt.org/t/ssl-on-a-ip-instead-of-domain/90635), so they require to use a domain name.
> 
> To make this work, you need to issue your certificates somewhere else, come back to the script, and when asked if you want to use certbot, you need to say NO. The you will be asked if you want to add your own certificates, and add them.
___

IS this the source of your problem maybe?

**Comment by paligiannis** [comment]
Before I would reply I wanted to be sure about the issue. I have installed 3-4 droplets and I see the same behavior. I follow the following tutorial step by step https://docs.meilisearch.com/create/how_to/digitalocean_droplet.html#configure-production-settings-in-your-meilisearch-droplet

1. I create the droplet -> ip given 46.101.87.138
2. I visit http://46.101.87.138 it works
3. I run meilisearch-setup 
4. I enter yes on the domain and enter my domain name goclumsy.gr
5. When i say install SSL by certbot -> 
Ok! Cool we'll setup SSL with Certbot
`Failed authorization procedure. goclumsy.gr (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://goclumsy.gr/.well-known/acme-challenge/lpWlWkMzumFm0BFYsm4sN5_R8FZtjhSMgchAMNzR55I [2606:4700:3035::ac43:b65a]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"`
6. I try to install my own credentials so I go to cloudflare -> create origin pems credentials and I pick I have my own credentials on setup
5. A record registered on cloudflare so http://droplet.goclumsy.gr should be availiable but it isn't -> the reply is **refused to connect.**

I can't figure our the issue and I don't want to leave meilisearch because it's such a great tool!

**Comment by eskombro** [comment]
I am really glad that you solved it @paligiannis, and would be really interested in knowing what happened and also this description of the issue may help someone else in the future!

**Comment by alallema** [comment]
I'm closing this issue because it is outdated. Feel free to reopen it if you need it.
