### ISSUE TITLE
Run test CI on ubuntu

### ISSUE THREAD

**Issue by nicolasvienot** [meilisearch/meilisearch-digitalocean#159]
Check comments on #157
[Located here](https://github.com/meilisearch/meilisearch-digitalocean/blob/main/.github/workflows/tests.yml#L18)

Currently, the test CI that build the image, test it and then destroy it is running on macos.
When running on ubuntu, the tests randomly fails when calling the digitalocean api through the python package digitalocean-python (at different locations):
`HTTPSConnectionPool(host='api.digitalocean.com', port=443): Read timed out.`
It is timed out after ~20min

This happens only when triggered by the Github Action with ubuntu runner.
- Ok with local env running macos 11.2.3.
- Ok with Github Action running macos-latest.
- Ok with VM running ubuntu-latest
- KO with Github Action running ubuntu-latest
- KO with Github Action running ubuntu-16

**Comment by curquiza** [comment]
Feel free to open a PR, a maintainer will let you run the CI once you submitted the changes.

**Comment by alallema** [comment]
Closing this issue due to the depreciation of this repository
