### ISSUE TITLE
CI failed randomly on `Build_image`

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-digitalocean#212]
**Description**
The CI failed during its automatic launch.

**Expected behavior**
Ci should pass every time

**Current behavior**
An error is raised [here an example on bump merge](https://github.com/meilisearch/meilisearch-digitalocean/runs/3130618318?check_suite_focus=true)

**Screenshots or Logs**
```
Run python3 tools/build_image.py $IMAGE_NAME
  python3 tools/build_image.py $IMAGE_NAME
  shell: /bin/bash -e {0}
  env:
    DIGITALOCEAN_ACCESS_TOKEN: 
    REQUEST_TIMEOUT_ENV_VAR: 30
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.7.11/x64
    IMAGE_NAME: meilisearch_digitalocean_ci_test_22-07-2021-04-16-02
Creating droplet...
Traceback (most recent call last):
  File "tools/build_image.py", line 20, in <module>
    droplet.create()
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/Droplet.py", line 568, in create
    data = self.get_data("droplets/", type=POST, params=data)
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/Droplet.py", line 165, in get_data
    data = super(Droplet, self).get_data(*args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/baseapi.py", line 216, in get_data
    req = self.__perform_request(url, type, params)
  File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/digitalocean/baseapi.py", line 92, in __perform_request
    raise TokenError("No token provided. Please use a valid token")
digitalocean.TokenError: No token provided. Please use a valid token
Error: Process completed with exit code 1.
```

**Comment by sanders41** [comment]
I think this could be related to [this](https://github.community/t/github-secrets-not-be-found/18007) GA bug.

On a run where it passes the variable is set:

```sh
  env:
    DIGITALOCEAN_ACCESS_TOKEN: ***
    REQUEST_TIMEOUT_ENV_VAR: 30
```

And when it fails it is not, matching the description of the bug:

```sh
env:
    DIGITALOCEAN_ACCESS_TOKEN: 
    REQUEST_TIMEOUT_ENV_VAR: 30
```

**Comment by alallema** [comment]
Thanks, @sanders41! It seems to be the same bug indeed.

**Comment by sanders41** [comment]
@alallema this workflow here is using `actions/checkout@v1`. I don't see anything about secrets in any of the v2 release notes, but maybe it's work a try to see if there was a fix in the latest version that just didn't make the release notes?

**Comment by sanders41** [comment]
@alallema are the failures always with dependabot, and if so does dependabot fail every time? If so I just happened to come across [this](https://github.com/dependabot/dependabot-core/issues/3253), maybe it could be related?

**Comment by alallema** [comment]
@sanders41 Yes indeed it fails every time with dependabot and sometimes with by manual trigger too but rarely.
Thanks for this resource so helpful I'll look into it

**Comment by alallema** [comment]
Since the last modification, there is no failure of the CI.
I closed this issue

**Comment by alallema** [comment]
Since the last modification, there is no failure of the CI.
I closed this issue
