### ISSUE TITLE
Unused requirements

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch-digitalocean#218]
I noticed while looking the the `requirements.txt` file that there are a lot of requirements that never get used. Some examples:

- asyncio - I don't see any async functions. Also asyncio is part of the standard library starting somewhere around Python 3.4.
- click - This is for CLIs but I don't see anything using it.
- Flask, Werkzeug, Jinja2 - I don't see any flask usage. I'm guessing the `requirements.txt` was generated with `pip freeze` and Werkzeug and Jinja2 were there as Flask requirements.

I didn't check every requirement, these are just some examples. Removing the unused requirements wouldn't fix the current dependabot/CI issue, but would at least cut down on the updates you need to do. As an added bonus the package size would be smaller and faster to install.

**Comment by alallema** [comment]
Oh, good point I'm going to clean this file. Thanks a lot @sanders41
