### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by diazsasak** [meilisearch/meilisearch-digitalocean#228]
**Describe the bug**
Hi, i deploy meilisearch from digitalocean provided droplet. I am facing problem saying that SSL certificate expired. how to update the SSL? i try to rerun meilisearch-setup and being asked to use ssl i choose "y". But still got this error. Some help would be appreciated, i got this error in production.

**Screenshots**
`"class": "GuzzleHttp\\Exception\\RequestException",
    "message": "cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://mydomain.com/indexes/my_invoices/documents?primaryKey=id"`

![image](https://user-images.githubusercontent.com/7880137/135560040-91bda50e-a5e3-4afe-82b4-e1156b21ee9e.png)
![image](https://user-images.githubusercontent.com/7880137/135589094-f4d12631-6f7c-4777-a38e-7df67046972d.png)

**MeiliSearch version:** 
0.19.0

**Additional context**
Meili Ubuntu droplet (provided by DigitalOcean)

**Comment by diazsasak** [comment]
Hello @curquiza , Thank you

**Comment by diazsasak** [comment]
Hello, i have found the solution and working. i need to update postman and disable the expired certificate on my server

https://github.com/postmanlabs/postman-app-support/issues/10338
https://superuser.com/questions/1679204/curl-on-ubuntu-14-all-lets-encrypt-certificates-are-expired-error-60

Thank you for your time

**Comment by alallema** [comment]
Hi @diazsasak,
I'm too late, sorry. Glad you found the solution, and thank you for the report.
I closed the issue feel free to reopen it if needed
