### ISSUE TITLE
Cannot Use One Click Image with $6 Droplet

### ISSUE THREAD

**Issue by devinnived** [meilisearch/meilisearch-digitalocean#299]
**Description**
Meilisearch's DO one click image cannot be used with a $6 droplet.

**Expected behavior**
Allow image to be used with a $6 droplet.

**Current behavior**
When attempting to create a droplet DO says "The size (25GB) does not have enough disk space to support the image you selected."

**Screenshots or Logs**
Link to screen recording of issue - https://drive.google.com/file/d/1aUL_A5MsmcdKFvjGgTeElfuKVQcUsZ4B/view?usp=sharing

Screenshot from DO support saying it is limited by Meilisearch.

<img width="723" alt="Screenshot 2022-10-31 at 09 16 14" src="https://user-images.githubusercontent.com/55025516/199018789-c6c8aea1-8aa6-43a3-85ca-bb54c89d0a0f.png">

**Environment (please complete the following information):**
Version 0.29.0 OS Ubuntu 20.04 (LTS) as stated on the App page here https://marketplace.digitalocean.com/apps/meilisearch

**Comment by brunoocasali** [comment]
For some reason, we changed the configuration a long time ago, and now I'm changing it back. I just submitted the new image to DO, and they need 2-3 business days to check that.

**Comment by brunoocasali** [comment]
It is working @devinnived now :)
