### ISSUE TITLE
Ssl

### ISSUE THREAD

**Issue by RafiRahmanRaif** [meilisearch/meilisearch-digitalocean#314]
#

**Description**
Brief explanation of the feature.

**Basic example**
If the proposal involves something new or a change, include a basic example. How would you use the feature? In which context?

**Other**
Any other things you want to add.

**Comment by alallema** [comment]
Hello @RafiRahmanRAIF,
Could you detail your issue? Is this a bug? A feature request?
Without a definition or description, I will have to delete this issue if it remains empty
Thank you
