### ISSUE TITLE
Document how to migrate to a new version in a droplet

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-digitalocean#50]
- updating meilisearch binary
- rm the DB in /var/lib/meilisearch
- restart the service
- repopulate the DB

**Comment by curquiza** [comment]
```bash
$ echo "deb [trusted=yes] https://apt.fury.io/meilisearch/ /" > /etc/apt/sources.list.d/fury.list
$ apt update && apt upgrade meilisearch-http
$ rm -rf /var/lib/meilisearch/data.ms
$ systemctl restart meilisearch
```

**Comment by eskombro** [comment]
This will be improved by https://github.com/meilisearch/MeiliSearch/issues/840

**Comment by curquiza** [comment]
Now the dumps are out, can we have a documentation about the migration? 🙂

**Comment by eskombro** [comment]
Yes @curquiza, we can, adding to TODO list ;)

**Comment by curquiza** [comment]
Already documented in the docs :) 🎉 
https://docs.meilisearch.com/create/how_to/updating.html#update-to-the-latest-meilisearch-version
