### ISSUE TITLE
Rename the "meilisearch-digital-ocean" folders into "meilisearch-digitalocean"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-digitalocean#64]
Following the renaming of this repository 👍

**Comment by curquiza** [comment]
I don't see anything that looks like "digital-ocean" in this repo. Can you confirm and close @eskombro?

**Comment by eskombro** [comment]
Confirmation: no `digital ocean:, no "digital-ocean". All the renaming is done ;)
