### ISSUE TITLE
Make the README point to the DO article in the MeiliSearch docs

### ISSUE THREAD

**Issue by fharper** [meilisearch/meilisearch-digitalocean#70]
The "How to deploy a MeiliSearch instance on DigitalOcean" part of the README should be in the documentation instead of the repo README. The README should point to the documentation.

**Comment by fharper** [comment]
@react-learner @eskombro by the way, I assigned both of you as I'm not sure how we will proceed for things like that, so please check together to see how you want to make it happen. Also, Tommy is the one who will decide where it should go in the doc.

**Comment by curquiza** [comment]
There is already an article about it -> https://docs.meilisearch.com/resources/howtos/digitalocean_droplet.html#how-to-deploy-a-meilisearch-instance-on-digitalocean.
Is this the kind of article you mentioned?
But yes, the README should definitely point to this article.

**Comment by fharper** [comment]
Oops, sorry, I missed it, but yeah, would be good to point there instead of having a duplicate. Always better to have one source of truth.

**Comment by eskombro** [comment]
Agreed, should be working on it very soon, so I will have this in mind, and probably request @react-learner for a review :)

**Comment by curquiza** [comment]
Closed by #128
