### ISSUE TITLE
Setting script MASTER KEY configuration on second+ run

### ISSUE THREAD

**Issue by fharper** [meilisearch/meilisearch-digitalocean#71]
Should "Do you wish to setup a MEILI_MASTER_KEY for your search engine [y/n]?" be something like "Do you wish to setup a **new** MEILI_MASTER_KEY for your search engine [y/n]?" when you run the script and you already have a master key?

I assume the master key isn't deleted when I run this script before I answer this question.

**Comment by curquiza** [comment]
Sam improves your suggestion by adding a green sentence explaining you already have a master key and if you want to set a new one 💪

**Comment by eskombro** [comment]
> Sam improves your suggestion by adding a green sentence explaining you already have a master key and if you want to set a new one 💪

Exactly. If a Master Key is detected, we will ask you if you want to re-use the same. If you refuse, we ask you to provide one, or we generate one automatically (assuming you said you want a Master Key in the first place)
